// Corrections applied to the supplied article batch on import.
//
// Ground truth comes from the live public model endpoint
// (https://model.service-inference.ai/public/models) — the same source
// scripts/verify-tm-models.ts checks the baked catalog against. NOTE: as of
// 2026-08-27 the baked lib/live-stats.json has drifted (it claims a 20% max
// discount; live reports 15%), so figures here are taken from live, not baked.

/**
 * Real pass-through discount on the current flagship line. Every LLM family on
 * the live endpoint reports discount_pct = 15. Higher values (30-40%) exist
 * only on legacy SKUs — gpt-4-turbo, deepseek-v3, glm-4.5 — and the site's own
 * liveMaxDiscountPct() returns 15.
 */
export const MAX_DISCOUNT_PCT = 15;

/** Reference (list) and TokenMart per-1M rates, from the live endpoint. */
export const RATES = {
  "Claude Opus 5": { in: 5, out: 25, tmIn: 4.25, tmOut: 21.25 },
  "Claude Sonnet 5": { in: 2, out: 10, tmIn: 1.7, tmOut: 8.5 },
  "Claude Haiku 4.5": { in: 1, out: 5, tmIn: 0.85, tmOut: 4.25 },
  "Claude Fable 5": { in: 10, out: 50, tmIn: 8.5, tmOut: 42.5 },
  "GPT-5.6 Sol": { in: 4, out: 20, tmIn: 3.4, tmOut: 17 },
  "GPT-5.5": { in: 5, out: 30, tmIn: 4.25, tmOut: 25.5 },
  "GPT-5.4": { in: 2.5, out: 15, tmIn: 2.125, tmOut: 12.75 },
  "Gemini 3.5 Flash": { in: 1.5, out: 9, tmIn: 1.275, tmOut: 7.65 },
  "Gemini 2.5 Pro": { in: 1.25, out: 10, tmIn: 1.0625, tmOut: 8.5 },
  "Grok 4.6": { in: 2, out: 6, tmIn: 1.7, tmOut: 5.1 },
  "DeepSeek V4 Pro": { in: 0.435, out: 0.87, tmIn: 0.37, tmOut: 0.74 },
};

/**
 * Models named in the batch that the live catalog no longer carries, mapped to
 * their current equivalent. Names NOT listed here were verified as real and are
 * left alone — including GPT-5.6 Sol/Terra/Luna, Grok 4.6/4.5/4.3,
 * Gemini 3.5 Flash / 3.1 Pro and GPT-4o, all of which an earlier audit pass
 * wrongly flagged as fabricated.
 */
export const STALE_MODELS = [
  [/\bClaude\s+3\.5\s+Sonnet\b/gi, "Claude Sonnet 5"],
  [/\bClaude\s+3\.7\s+Sonnet\b/gi, "Claude Sonnet 5"],
  [/\bClaude\s+3\.5\s+Haiku\b/gi, "Claude Haiku 4.5"],
  [/\bClaude\s+3\s+Haiku\b/gi, "Claude Haiku 4.5"],
  [/\bClaude\s+3\.5\s+Opus\b/gi, "Claude Opus 5"],
  [/\bClaude\s+3\s+Opus\b/gi, "Claude Opus 5"],
  [/\bGemini\s+1\.5\s+Flash\b/gi, "Gemini 3.5 Flash"],
  [/\bGemini\s+1\.5\s+Pro\b/gi, "Gemini 3.1 Pro"],
  [/\bGemini\s+2\.0\s+Flash\b/gi, "Gemini 3.5 Flash"],
  [/\bGPT-3\.5(?:\s+Turbo)?\b/gi, "GPT-5.4"],
];

/**
 * Commitments the company has not published and could be held to. Each entry
 * replaces the specific promise with language the catalog supports.
 */
export const UNSUPPORTED_CLAIMS = [
  [/\b99\.9+\s*%\s*(?:uptime|availability|SLA)\b/gi, "production-grade uptime"],
  [/\boffering 99\.9+\s*%/gi, "offering production-grade uptime"],
  [/,?\s*zero[- ]added latency,?/gi, " "],
  [/\bzero[- ]latency\b/gi, "low-latency"],
  [/\bwill absolutely not slow down your software application\b/gi,
    "adds only a thin routing hop"],
  [/\bSOC ?2[- ]?(?:Type ?(?:I{1,2}|\d))?\s*(?:compliant|certified|compliance)\b/gi,
    "enterprise security practices"],
  [/\bfully GDPR[- ]compliant\b/gi, "mindful of GDPR obligations"],
  [/\b(?:zero|no) rate[- ]limit(?:ing|s)?\b/gi, "generous rate limits"],
];

// NOTE: savings claims are deliberately NOT handled by regex here.
//
// An earlier version capped every "up to N%" inside a sentence that mentioned
// the brand. It failed in both directions: it rewrote only 1 of 25 real
// over-claims (most offending sentences never name us explicitly), and it
// corrupted true statements — "Prompt Caching and the Batch API reduce base
// token costs by up to 90% and 50%, respectively" became "up to 15%", turning
// an accurate industry fact into a false one.
//
// Deciding whether a percentage is a provider-side fact or a promise we are
// making needs the surrounding argument, so those edits are produced by
// scripts/claim-edits.json (generated by a review pass) and applied verbatim.

/**
 * Two title pairs arrive identical (#56/#63 and #84/#94), which would collide on
 * slug and compete for the same query. The bodies differ — #63 leans on a
 * GPT/Claude/Gemini model comparison and #94 on the buying process — so each is
 * retitled to the angle it actually covers rather than one being dropped.
 */
export const TITLE_OVERRIDES = {
  63: "Cheapest LLM API in 2026: GPT vs Claude vs Gemini Compared",
  94: "How to Buy Cheaper Claude and OpenAI API Tokens in 2026",
};

/** Structural repairs for the two articles whose Markdown does not parse. */
export const STRUCTURAL = [
  // #48: a doubled heading marker renders the literal text "## Frequently...".
  [/^##\s+##\s+/gm, "## "],
  // #68: every H2 is wrapped in bold with the hashes inside the asterisks, so
  // none of them parses as a heading.
  [/^\*\*##\s*(.+?)\s*\*\*\s*$/gm, "## $1"],
  [/^\*\*###\s*(.+?)\s*\*\*\s*$/gm, "### $1"],
  // Generator scaffolding left as a visible bold label.
  [/^\*\*(Introduction|Conclusion)\*\*\s*$/gm, "## $1"],
];

/**
 * Apply every deterministic correction. Order matters: structure first so
 * headings parse, then model names, then unsupported commitments. Savings
 * claims are handled separately — see the note above.
 */
export function applyFixes(text) {
  let out = text;
  for (const [re, to] of STRUCTURAL) out = out.replace(re, to);
  for (const [re, to] of STALE_MODELS) out = out.replace(re, to);
  for (const [re, to] of UNSUPPORTED_CLAIMS) out = out.replace(re, to);
  return out.replace(/[ \t]{2,}/g, " ").replace(/ +([,.])/g, "$1");
}
